### ISSUE TITLE
Symfony 4 update

### ISSUE THREAD

**Issue by ivan-jovanovic** [fungio/FungioGoogleCalendarBundle#1]
Hello,

I was wondering if you are planning to make the necessary  updates to your plugin so that it will be compatible to Symfony 4? This version of the plugin will no longer work in Symfony 4. 
This is the error that it gives:
`
Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "fungio.google_calendar" service to "Fungio\GoogleCalendarBundle\Service\GoogleCalendar" instead.`

**Comment by fungio** [comment]
Hello. I'll probably make an update soon but feel free to create a pull request
