### ISSUE TITLE
Attempted to call an undefined method named "getRootNode"

### ISSUE THREAD

**Issue by jdessaint** [fungio/FungioGoogleCalendarBundle#4]
Hi,

I tried to install your bundle and everything was OK.

But when i can't start the server, i have the current error:

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getRootNode" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder". in /vendor/fungio/google-calendar-bundle/Fungio/GoogleCalendarBundle/DependencyInjection/Configuration.php:21`

Could you help me ?

I'm on linux and i use Symfony 3.4

Thanks

**Comment by fungio** [comment]
Fixed in 41970c8573938b04ac85ebce93c2974c6cf55d85
You got to use en branch 3.x though
