### ISSUE TITLE
Symfony 3.4.x

### ISSUE THREAD

**Issue by jestep** [fungio/FungioGoogleCalendarBundle#5]
Is Symfony 3.4 no longer supported for this bundle? Composer is throwing a "fungio/google-calendar-bundle dev-master requires symfony/framework-bundle 4.*" error when I try to install it on 3.4.36.

Thanks
Jamie

**Comment by fungio** [comment]
Hi! You have to require the 3.x version if you want to use it in a Symfony 3 project
https://packagist.org/packages/fungio/google-calendar-bundle#3.x-dev

**Comment by jestep** [comment]
Sorry, the instruction on packagist for both versions shows:
composer require fungio/google-calendar-bundle:dev-master

composer require fungio/google-calendar-bundle:3.x-dev worked fine, appreciate the quick reply, I should have caught that.

**Comment by fungio** [comment]
Indeed. I updated the README file
Thx
